import type { GarmentRecord } from "@/lib/types";

export const demoGarments: GarmentRecord[] = [
  {
    id: "demo-1",
    name: "Navy Wool Overcoat",
    category: "Outerwear",
    brand: "Theory",
    size: "M",
    primary_color: "Navy",
    secondary_colors: ["Charcoal"],
    pattern: "Solid",
    style_tags: ["tailored", "winter", "minimal"],
    season: ["fall", "winter"],
    occasion: ["work", "formal"],
    fit: "Relaxed tailored",
    material_composition: [
      { material: "Wool", percentage: 80 },
      { material: "Cashmere", percentage: 20 },
    ],
    care_instructions: ["Dry clean only"],
    confidence: 0.94,
    image_url:
      "https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?auto=format&fit=crop&w=1200&q=80",
    tag_image_url: null,
    notes: "Best paired with dark denim or tailored trousers.",
    created_at: new Date("2026-03-01T09:00:00Z").toISOString(),
    last_worn_at: new Date("2026-03-29T09:00:00Z").toISOString(),
  },
  {
    id: "demo-2",
    name: "Off-White Heavy Tee",
    category: "Tops",
    brand: "Cos",
    size: "L",
    primary_color: "Ecru",
    secondary_colors: [],
    pattern: "Solid",
    style_tags: ["essential", "layering", "casual"],
    season: ["spring", "summer"],
    occasion: ["casual", "travel"],
    fit: "Oversized",
    material_composition: [{ material: "Cotton", percentage: 100 }],
    care_instructions: ["Machine wash cold", "Tumble dry low"],
    confidence: 0.89,
    image_url:
      "https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=1200&q=80",
    tag_image_url: null,
    notes: "Easy rotation piece for layered fits.",
    created_at: new Date("2026-03-08T09:00:00Z").toISOString(),
    last_worn_at: new Date("2026-04-04T09:00:00Z").toISOString(),
  },
  {
    id: "demo-3",
    name: "Stone Utility Trouser",
    category: "Bottoms",
    brand: "A.P.C.",
    size: "32",
    primary_color: "Stone",
    secondary_colors: ["Sand"],
    pattern: "Solid",
    style_tags: ["utility", "clean", "smart-casual"],
    season: ["spring", "fall"],
    occasion: ["work", "weekend"],
    fit: "Straight",
    material_composition: [
      { material: "Cotton", percentage: 97 },
      { material: "Elastane", percentage: 3 },
    ],
    care_instructions: ["Machine wash cold", "Line dry"],
    confidence: 0.91,
    image_url:
      "https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=1200&q=80",
    tag_image_url: null,
    notes: "Works well with loafers or sneakers.",
    created_at: new Date("2026-03-15T09:00:00Z").toISOString(),
    last_worn_at: new Date("2026-04-07T09:00:00Z").toISOString(),
  },
  {
    id: "demo-4",
    name: "Washed Indigo Shirt",
    category: "Shirts",
    brand: "J.Crew",
    size: "M",
    primary_color: "Indigo",
    secondary_colors: ["Blue"],
    pattern: "Tonal",
    style_tags: ["relaxed", "layering", "weekend"],
    season: ["spring", "summer", "fall"],
    occasion: ["casual", "travel"],
    fit: "Regular",
    material_composition: [{ material: "Lyocell", percentage: 100 }],
    care_instructions: ["Machine wash cold", "Hang dry"],
    confidence: 0.88,
    image_url:
      "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?auto=format&fit=crop&w=1200&q=80",
    tag_image_url: null,
    notes: "Nice open over a tee or tucked into trousers.",
    created_at: new Date("2026-03-19T09:00:00Z").toISOString(),
    last_worn_at: new Date("2026-04-02T09:00:00Z").toISOString(),
  },
  {
    id: "demo-5",
    name: "Black Leather Sneaker",
    category: "Shoes",
    brand: "Common Projects",
    size: "42",
    primary_color: "Black",
    secondary_colors: ["White"],
    pattern: "Solid",
    style_tags: ["minimal", "street", "premium"],
    season: ["spring", "fall", "winter"],
    occasion: ["casual", "travel"],
    fit: null,
    material_composition: [{ material: "Leather", percentage: 100 }],
    care_instructions: ["Wipe clean", "Condition leather periodically"],
    confidence: 0.87,
    image_url:
      "https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=1200&q=80",
    tag_image_url: null,
    notes: "Low-profile silhouette keeps fits clean.",
    created_at: new Date("2026-03-23T09:00:00Z").toISOString(),
    last_worn_at: new Date("2026-04-08T09:00:00Z").toISOString(),
  },
  {
    id: "demo-6",
    name: "Midnight Knit Polo",
    category: "Tops",
    brand: "Mango",
    size: "M",
    primary_color: "Midnight",
    secondary_colors: ["Blue"],
    pattern: "Micro texture",
    style_tags: ["elevated casual", "knit", "date-night"],
    season: ["spring", "summer", "fall"],
    occasion: ["dinner", "work"],
    fit: "Slim",
    material_composition: [
      { material: "Viscose", percentage: 72 },
      { material: "Polyamide", percentage: 28 },
    ],
    care_instructions: ["Hand wash cold", "Lay flat to dry"],
    confidence: 0.9,
    image_url:
      "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=1200&q=80",
    tag_image_url: null,
    notes: "Premium texture gives the app a more elevated wardrobe feel.",
    created_at: new Date("2026-03-30T09:00:00Z").toISOString(),
    last_worn_at: new Date("2026-04-10T09:00:00Z").toISOString(),
  },
];
